src/main/java/com/my/relink/controller/TradeController.java
src/main/java/com/my/relink/domain/point/Point.java
src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepository.java
src/main/java/com/my/relink/domain/point/repository/PointRepository.java
src/main/java/com/my/relink/domain/trade/Trade.java
src/main/java/com/my/relink/domain/trade/dto/TradeRequestDto.java
src/main/java/com/my/relink/domain/trade/dto/TradeRequestResponseDto.java
src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
src/main/java/com/my/relink/domain/user/repository/UserRepository.java
src/main/java/com/my/relink/ex/ErrorCode.java
src/main/java/com/my/relink/service/TradeService.java
src/main/java/com/my/relink/util/api/ApiError.java
src/main/java/com/my/relink/util/api/ApiResult.java

사용자가 교환을 신청하는 기능
- Closes #11
- Resolves #11 
1. 로그인 유저의 포인트를 조회해서 잔액 차감
2. point history 생성
3. 로그인 유저가 거래의 요청자라면  has_requester_requested를 true로 설정
4. 로그인 유저가 거래의 요청자가 아니면 has_owner_requested를 true로 설정
5. 요청자와 등록자의 xxx_requested 필드가 둘 다 true인지 검증
6. 둘 다 true라면 tradeStatus를 IN_EXCHANGE 로 설정
apiresult와 apierror 코드는 이전에 사용했던 코드를 그대로 작성한 거라 빼고 검토해주시면 감사하겠습니다.

Feat: 교환 신청

---

src/main/java/com/my/relink/config/security/AuthUser.java
src/main/java/com/my/relink/config/security/jwt/JwtProvider.java

- Open #58 
1. JWT Provider 에서 토큰 생성 시 authentication 에서 id 값을 추출 후 토큰 생성 
2. AuthUser id 필드 추가

REFACTOR: 토큰에 ID 값 추가 

---

src/main/java/com/my/relink/domain/BaseEntity.java

BaseEntity 어노테이션 누락 
- Open #62 
1. BaseEntity 에 MappedSuperclass 추가

FIX: BaseEntity 오류 해결 

---

src/main/java/com/my/relink/controller/user/UserController.java
src/main/java/com/my/relink/controller/user/dto/resp/UserAddressRespDto.java
src/main/java/com/my/relink/service/UserService.java
src/test/java/com/my/relink/service/UserServiceTest.java

- OPEN #56 
- Resolves #
1. 토큰에서 UserId 찾는다. 
2. UserId 로 해당 사용자의 주소를 찾은 후 주소 응답

FEAT: 사용자 주소 조회 기능 구현 

---

src/main/java/com/my/relink/controller/user/UserController.java
src/main/java/com/my/relink/controller/user/dto/resp/UserPointRespDto.java
src/main/java/com/my/relink/domain/point/Point.java
src/main/java/com/my/relink/service/UserService.java
src/test/java/com/my/relink/service/UserServiceTest.java

사용자 포인트 조회 
- OPEN #57 
1. 사용자 포인트 조회 전 토큰에서 사용자 ID를 통해 DB 조회 
2. 조회한 사용자로 Point 조회 후 응답

FEAT: 사용자 포인트 조회 기능 구현 

---

src/main/java/com/my/relink/controller/trade/TradeController.java
src/main/java/com/my/relink/controller/trade/dto/response/TradeCompleteRespDto.java
src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepository.java
src/main/java/com/my/relink/domain/trade/Trade.java
src/main/java/com/my/relink/service/PointTransactionService.java
src/main/java/com/my/relink/service/TradeService.java

사용자가 교환 물품을 받았을 때 수령 완료했음을 알리기 위해 버튼 누를 때 호출
- Closes #15 
- Resolves #15 
1. 로그인 유저가 requester라면 has_requeter_received를 true로 설정
2. 아니라면 has_owner_received를 true로 설정
3. received 필드가 모두 true라면 tradeStatus를 EXCHANGED로 변경
4. 해당 거래 아이디를 갖는 포인트 이력이 있는지 확인
5. amount가 거래 아이템의 보증금과 일치하는지 type이 일치하는지 확인
6. 아직 환급되지 않은 경우에만 환급 처리
7. 환급 이력 생성
아직 알림기능이 구현되지 않아 그부분은 제외하고 봐주세요~

Feat : 교환 수락하기 - 수령 완료 누르기

---

src/main/java/com/my/relink/controller/user/dto/req/AddressCreateReqDto.java
src/main/java/com/my/relink/controller/user/dto/req/UserCreateReqDto.java

사융자 주소 선택 사항 
- OPEN #79 
1. Address nullable

FIX : 사용자 주소 선택 사항

---

src/main/java/com/my/relink/config/JpaConfig.java

@EnableJpaAuditing 누락으로 인해 Auditing이 작동하지 않음을 발견
따라서 이를 추가한다
- Closes #88
- 아래 설정을 추가
``` java
@Configuration
@EnableJpaAuditing
public class JpaConfig {
}
```

FIX: EnableJpaAuditing 설정 누락

---

src/main/java/com/my/relink/domain/trade/TradeStatus.java

TradeStatus에 교환 불가능 enum을 추가한다
- Closes #91
- Resolves #

FEAT: 교환 불가능 상태 추가

---

src/main/java/com/my/relink/util/DummyObject.java
src/test/java/com/my/relink/service/TradeServiceTest.java

- Closes #84 
- Resolves #84 
1. 교환 신청 성공 테스트
2. 교환 신청 취소 성공 테스트
3. 교환 수락 시 주소 입력 성공 테스트
4. 교환 수령 완료 성공 테스트

Test : 교환 도메인 테스트

---

src/main/java/com/my/relink/controller/like/LikeController.java
src/main/java/com/my/relink/controller/like/dto/resp/LikeExchangeItemListRespDto.java
src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
src/main/java/com/my/relink/domain/like/Like.java
src/main/java/com/my/relink/domain/like/repository/CustomLikeRepository.java
src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
src/main/java/com/my/relink/domain/like/repository/LikeRepository.java
src/main/java/com/my/relink/domain/like/repository/dto/LikeExchangeItemListRepositoryDto.java
src/main/java/com/my/relink/domain/trade/Trade.java
src/main/java/com/my/relink/service/LikeService.java
src/main/java/com/my/relink/service/UserService.java
src/main/java/com/my/relink/util/page/PageInfo.java
src/main/java/com/my/relink/util/page/PageResponse.java
src/test/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImplTest.java

관심 상품 목록 조회 기능 
- OPEN #54 
1. Queyry dsl 을 이용하여 사용자 Id 로 Like table, Exchange Item table 에서 값 찾기 
2. 사용자 신뢰도는 평균 평점을 연산하여 응답 
3. 신뢰도는 애플리케이션 계층에서 수행

FEAT: 내 관심 상품 목록 조회 기능 구현 

---

src/main/java/com/my/relink/controller/report/ReportController.java
src/main/java/com/my/relink/controller/report/dto/request/ExchangeItemReportCreateReqDto.java
src/main/java/com/my/relink/ex/ErrorCode.java
src/main/java/com/my/relink/service/ExchangeItemService.java
src/main/java/com/my/relink/service/ReportService.java
src/test/java/com/my/relink/service/ReportServiceTest.java

교환 상품 신고 기능을 구현한다
- Opens #104
* api:  /items/exchanges/{itemId}/report
*** 한 교환 상품에 대해 여러 신고 접수가 가능하다
1. 해당 아이템을 조회한다 -> 존재하지 않을 시 에러 throw
2. 해당 아이템 주인을 신고 대상 유저로 설정한다
3. 해당 신고 객체를 생성한 뒤 저장한다
reportService
- 교환 상품 신고에 성공한다
- 존재하지 않는 교환 상품 id를 신고 시 예외가 발생한다

FEAT: 교환 상품 신고하기

---

src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
src/main/java/com/my/relink/domain/user/User.java

User 클래스와 ExchangeItem의 @SQLRestriction을 제거한다
- Closes #117
- Resolves #

REFACTOR: User/ExchangeITem 클래스의 @SQLRestriction 제거

---

src/main/java/com/my/relink/domain/image/repository/CustomImageRepositoryImpl.java

CustomImageRepositoryImpl 네이밍 오타 수정
- Closes #136
- Resolves #
1. CustomImageRepositoryImpl 네이밍 오타 수정
2.

Refactor : CustomImageRepositoryImpl 네이밍 오타 수정

---

src/main/java/com/my/relink/controller/trade/TradeController.java
src/main/java/com/my/relink/controller/trade/dto/response/ViewReviewRespDto.java
src/main/java/com/my/relink/controller/trade/dto/response/ViewTradeCancelRespDto.java
src/main/java/com/my/relink/service/TradeService.java
src/test/java/com/my/relink/service/TradeServiceTest.java

리뷰 페이지에 들어가면 거래에 대한 정보 조회
- Closes #108 
- Resolves #108 
1. 거래 리뷰 페이지에 들어간다
2. 거래에 대한 정보가 상단에 위치한다.
- 거래 id
- 상품 이미지
- 상품명
- 상대 닉네임
- 교환 완료일

Feat : 리뷰 페이지 조회

---

build.gradle
src/main/java/com/my/relink/config/s3/S3Config.java
src/main/java/com/my/relink/config/s3/S3Service.java
src/main/java/com/my/relink/controller/user/UserController.java
src/main/java/com/my/relink/ex/ErrorCode.java
src/main/java/com/my/relink/service/UserService.java
src/main/resources/application-dev.yaml
src/test/java/com/my/relink/service/UserServiceTest.java

- OPEN #131 
1. 이미지 등록 코드 추가 
2. 이미지 삭제 코드 추가

FEAT: S3 Config 추가 

---

src/main/java/com/my/relink/controller/image/ImageController.java
src/main/java/com/my/relink/controller/image/dto/resp/ImageUserProfileCreateRespDto.java
src/main/java/com/my/relink/ex/ErrorCode.java
src/main/java/com/my/relink/service/ImageService.java
src/test/java/com/my/relink/service/ImageServiceTest.java

사용자 프로필 사진 등록 
- OPEN #129 
1. MultiPart로 사진등록을 합니다. 
2. 등록 후 Image Id, Image Url 정보를 응답합니다.

FEAT: 사용자 프로필 사진 등록 기능

---

src/main/java/com/my/relink/service/LikeService.java

순환참조 발생 관련 코드 수정
- Closes #165
1. 순환참조 발생 관련 코드 수정

Refactor : 순환참조 발생 관련 코드 수정

---

src/main/java/com/my/relink/client/tosspayments/TossPaymentClient.java
src/main/java/com/my/relink/client/tosspayments/dto/request/TossPaymentReqDto.java
src/main/java/com/my/relink/client/tosspayments/dto/response/TossPaymentRespDto.java
src/main/java/com/my/relink/client/tosspayments/feature/PaymentFeature.java
src/main/java/com/my/relink/client/tosspayments/feature/PaymentStatus.java
src/main/java/com/my/relink/controller/payment/PaymentController.java
src/main/java/com/my/relink/controller/payment/dto/request/PaymentReqDto.java
src/main/java/com/my/relink/controller/payment/dto/response/PaymentRespDto.java
src/main/java/com/my/relink/domain/payment/Payment.java
src/main/java/com/my/relink/domain/payment/PaymentCancelReason.java
src/main/java/com/my/relink/domain/payment/PaymentType.java
src/main/java/com/my/relink/domain/payment/repository/PaymentRepository.java
src/main/java/com/my/relink/domain/point/Point.java
src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
src/main/java/com/my/relink/ex/ErrorCode.java
src/main/java/com/my/relink/service/PointService.java
src/main/java/com/my/relink/service/payment/PaymentCancelReason.java
src/main/java/com/my/relink/service/payment/PaymentService.java
src/main/java/com/my/relink/service/payment/PaymentServiceFacade.java
src/main/java/com/my/relink/service/payment/dto/PaymentValidation.java
src/main/java/com/my/relink/service/payment/ex/PaymentCancelFailException.java
src/main/resources/templates/charge/charge-success.html
src/test/java/com/my/relink/service/payment/PaymentServiceTest.java

- 포인트 충전을 위한 결제 서비스를 구현한다
- PaymentProcessService를 위한 선행 작업을 준비한다
- Opens #127
- 추후 PaymentProcessService에서 사용될 기본 메서드들 구현
- 결제 정보 저장
- 포인트 충전
- 결제 검증
- 결제 취소
- 실패 시 복구
- 상태 변경
각 메서드의 책임을 분리하고 실패 케이스에 대한 예외 처리와 복구 로직을 넣다보니 파일 변경사항이 많아졌습니다..
현재 구현한 내용은 추후 다음과 같이 사용될 예정입니다
ex)
```java
@Service
@Transactional
public class PaymentProcessService {
private final PaymentService paymentService;
public PointChargeResult processPayment(PaymentReqDto reqDto) {
// 1. 사용자 및 결제 정보 검증
User user = paymentService.validateUserAndPayment(reqDto);
// 2. 결제 정보 저장
Payment payment = paymentService.savePaymentInfo(reqDto, respDto, user);
// 3. 포인트 충전
PointHistory history = paymentService.chargePointWithHistory(user, payment);
// 4. 결제 실패 시 자동 취소
// PaymentService 내부에서 처리
}
}
```
추후 PaymentProcessService에서의 트랜잭션 …

Feat: 포인트 충전을 위한 결제 서비스 구현

---

src/main/java/com/my/relink/controller/donation/DonationController.java
src/main/java/com/my/relink/controller/donation/dto/resp/DonationItemDetailRespDto.java
src/main/java/com/my/relink/domain/item/donation/DonationItem.java
src/main/java/com/my/relink/domain/item/donation/repository/DonationItemRepository.java
src/main/java/com/my/relink/ex/ErrorCode.java
src/main/java/com/my/relink/service/DonationItemService.java

기부 상품 상세 페이지 
- Closes #25
- Resolves #25 
1. 기부 상세 내역을 조회할 수 있습니다.

Feat : 기부 상품 상세 페이지

---

src/main/java/com/my/relink/controller/donation/DonationController.java
src/main/java/com/my/relink/controller/donation/dto/req/DonationItemRejectReqDto.java
src/main/java/com/my/relink/domain/item/donation/DonationItem.java
src/main/java/com/my/relink/service/DonationItemService.java

기부 알림 검수 부적합: 반송 여부
- Closes #31 
- Resolves #31
1. 기부 물품이 검수 후 부적합 했다고 알림이 떴을때, 사용자에게 반송 여부를 물어보고 주소를 받는 기능

Feat: 기부 알림 검수 부적합: 반송 여부

---

src/main/java/com/my/relink/controller/image/ImageController.java
src/main/java/com/my/relink/domain/image/repository/ImageRepository.java
src/main/java/com/my/relink/domain/item/donation/repository/DonationItemRepository.java
src/main/java/com/my/relink/ex/ErrorCode.java
src/main/java/com/my/relink/service/ImageService.java

기부 상품 사진등록
- Closes #28 
- Resolves #28 
1. 기부상품 사진을 등록합니다.
2. 사용자가 올린 상품인지 확인합니다.
3. 이미지는 최대 5장까지만 가능합니다.

Feat : 기부 상품 사진등록

---

src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
src/main/java/com/my/relink/service/ExchangeItemService.java
src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
src/test/java/com/my/relink/service/TradeServiceTest.java

교환할 내 물품 선택 오타 및 코드 수정
- Closes #196
교환할 내 물품 선택 오타 및 코드 수정
ExchangeItemServiceTest 전체 테스트 성공

Refactor : 교환할 내 물품 선택 오타 및 코드 수정

---

src/main/java/com/my/relink/controller/image/ImageController.java
src/main/java/com/my/relink/service/ImageService.java

기부 상품 사진 삭제
- Closes #29
- Resolves #29
- 
1. 기부 상품 사진을 삭제하는 기능 구현

Feat : 기부 상품 사진 삭제

---

src/main/java/com/my/relink/chat/service/ChatService.java
src/main/java/com/my/relink/domain/image/repository/CustomImageRepository.java
src/main/java/com/my/relink/domain/image/repository/CustomImageRepositoryImpl.java
src/main/java/com/my/relink/domain/image/repository/ImageRepository.java
src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepository.java
src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
src/main/java/com/my/relink/domain/like/repository/CustomLikeRepository.java
src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
src/main/java/com/my/relink/domain/like/repository/LikeRepository.java
src/main/java/com/my/relink/domain/message/repository/CustomMessageRepository.java
src/main/java/com/my/relink/domain/message/repository/CustomMessageRepositoryImpl.java
src/main/java/com/my/relink/domain/message/repository/MessageRepository.java
src/main/java/com/my/relink/service/ExchangeItemService.java
src/main/java/com/my/relink/service/ImageService.java
src/main/java/com/my/relink/service/LikeService.java
src/main/java/com/my/relink/service/UserService.java
src/test/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepositoryTest.java
src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
src/test/java/com/my/relink/service/ImageServiceTest.java
src/test/java/com/my/relink/service/LikeServiceTest.java
src/test/java/com/my/relink/service/UserServiceTest.java

기존 Query를 QueryDSL로 변경
- Closes #208
- Resolves #210
기존 Query를 QueryDSL로 변경

Refactor : QueryDSL 변경작업

---

.github/workflows/pr-trigger.yml
build.gradle

- OPEN #205
1. 환경 변수 추가 
2. 권한 설정 
3. build, test 할 수 있도록 설정

FEAT: Github Action CI 파일 추가 

---

build.gradle
src/main/java/com/my/relink/config/MetricConfig.java
src/main/java/com/my/relink/config/security/JwtAuthorizationFilter.java
src/main/java/com/my/relink/config/security/config/SecurityConfig.java
src/main/java/com/my/relink/service/DonationItemService.java
src/main/java/com/my/relink/service/ExchangeItemService.java
src/main/java/com/my/relink/service/ReviewService.java
src/main/java/com/my/relink/service/TradeService.java
src/main/java/com/my/relink/service/UserService.java
src/main/java/com/my/relink/service/UserTrustScoreService.java
src/main/java/com/my/relink/util/MetricConstants.java
src/main/resources/application-dev.yaml

메트릭을 수집하기 위한 기반 작업입니다. 
- OPEN #212 
모니터링을 위한 메트릭 설정입니다.

FEAT: 메트릭 수집 설정 

---

src/main/java/com/my/relink/controller/donation/DonationController.java
src/main/java/com/my/relink/controller/donation/dto/resp/DonationItemDetailRespDto.java
src/main/java/com/my/relink/domain/item/donation/repository/CustomDonationItemRepository.java
src/main/java/com/my/relink/domain/item/donation/repository/CustomDonationItemRepositoryImpl.java
src/main/java/com/my/relink/domain/item/donation/repository/DonationItemRepository.java
src/main/java/com/my/relink/service/DonationItemService.java
src/main/java/com/my/relink/service/ImageService.java

기부 관련 QueryDSL로 변경
- Closes #211 
- Resolves #
1. 기부 관련 쿼리들 Querydsl로 변경
2. ImageService 의 getImagesByItemIds 변경

Refactor : 기부 관련 QueryDSL로 변경

---

src/main/java/com/my/relink/chat/service/ChatService.java
src/main/java/com/my/relink/domain/image/repository/CustomImageRepositoryImpl.java
src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
src/main/java/com/my/relink/domain/message/repository/CustomMessageRepositoryImpl.java
src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepository.java
src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepositoryImpl.java
src/main/java/com/my/relink/service/DonationItemService.java
src/main/java/com/my/relink/service/ExchangeItemService.java
src/main/java/com/my/relink/service/ImageService.java
src/main/java/com/my/relink/service/LikeService.java
src/main/java/com/my/relink/service/TradeService.java
src/test/java/com/my/relink/service/ExchangeItemServiceTest.java

교환 상품 삭제 시 거래 삭제 구현
- Closes #210
교환 상품 삭제 시
1. 해당 상품과 관련된 거래 정보가 있는지 확인
2. 해당 거래 상품의 상품과 삭제할 교환상품을 비교하여 거래 대상의 아이템을 확인
3. 거래 대상의 아이템을 통하여 거래대상의 아이템이 삭제상태인지, 거래상대가 탈퇴했는지 확인
4. 거래를 삭제
외 오타 및 작은 사항들 수정

Refactor : 교환 상품 삭제 시 거래 삭제

---

src/main/java/com/my/relink/service/DonationItemService.java

- Closes #224 
- Resolves #224
- 기부 완료 알림
- 기부 부적합 알림
- 기부 상품 반송여부 알림

Feat : 기부 관련 알림 발행

---

src/main/java/com/my/relink/common/notification/NotificationPublisherService.java
src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
src/main/java/com/my/relink/controller/exchangeItem/dto/resp/FindAllExchangeItemListRespDto.java
src/main/java/com/my/relink/controller/user/UserController.java
src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepository.java
src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
src/main/java/com/my/relink/domain/item/exchange/repository/dto/FindExchangeItemListRepositoryDto.java
src/main/java/com/my/relink/domain/review/Review.java
src/main/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImpl.java
src/main/java/com/my/relink/service/ExchangeItemService.java
src/main/java/com/my/relink/service/ReviewService.java
src/test/java/com/my/relink/domain/review/repository/CustomReviewRepositoryTest.java

QueryDsl 을 이용한 성능 개선 
- OPEN #227
1. 인덱스를 활용하여 쿼리 성능 개선 
2. v0/v1/v2 버전으로 사용 
참고 자료 : https://www.notion.so/teamsparta/QueryDsl-a10f1a8057164bdd81e8a0c83f28865d

[REFACTOR] : QueryDsl 성능 개선 

---

.github/workflows/pr-trigger.yml
src/main/resources/appication-prod.yml
src/main/resources/application-dev.yaml
src/main/resources/application.yaml

- OPEN #237
1. yml 파일 추가 
2. ci 파일 수정

[DEPLOY] 배포 CI/CD 적용 

---

src/main/resources/logback-spring.xml

dev profile 로깅 레벨 조정
- Closes #234
- Resolves #
1) Hibernate 로깅 레벨 조정
- org.hibernate: WARN → INFO
- org.hibernate.SQL: WARN → INFO
- org.hibernate.orm.jdbc.bind: WARN → TRACE 
- org.hibernate.type 로거 제거
2) 애플리케이션 로깅 레벨 조정
- com.my.relink: INFO → DEBUG (애플리케이션 상세 로깅)
3) Spring Framework 로깅 추가
- org.springframework: INFO 레벨 로깅 추가

REFACTOR: dev profile 로깅 레벨 조정

---

src/main/resources/application-prod.yaml

[CHORE]: yaml 확장자 변경  
